import { mkdir, readFile, writeFile, cp, readdir } from 'node:fs/promises';
import { resolve, join } from 'node:path';
import { projects, contributions } from '../src/content.mjs';

const root = resolve(import.meta.dirname, '..');
const output = join(root, 'dist');
await mkdir(output, {recursive:true});
await cp(join(root, 'public'), output, {recursive:true});
await cp(join(root, 'CNAME'), join(output, 'CNAME'));
await writeFile(join(output,'.nojekyll'),'');
const arrow = '<span aria-hidden="true">↗</span>';
const ext = (label, href) => `<a class="text-link" href="${href}" target="_blank" rel="noopener noreferrer">${label} ${arrow}</a>`;
const tags = items => `<ul class="tags" aria-label="Technologies">${items.map(item=>`<li>${item}</li>`).join('')}</ul>`;
const sectionHead = (n, title, aside='') => `<div class="section-heading"><div><span class="index">${n}</span><h2>${title}</h2></div>${aside}</div>`;
const projectRows = projects.map(p=>`<a class="project-row" href="/work/${p.slug}/"><span class="index">${p.number}</span><div><span class="meta">${p.category}</span><h3>${p.title}</h3><p>${p.summary}</p></div><span class="row-arrow" aria-hidden="true">↗</span></a>`).join('');
const ossRows = contributions.map(c=>`<article class="oss-row"><div><span class="meta">${c.tech}</span><h3>${c.name}</h3><a class="pr-link" href="https://github.com/${c.repo}/pull/${c.number}" target="_blank" rel="noopener noreferrer">Merged PR #${c.number} ${arrow}</a></div><div><h4>${c.title}</h4><p>${c.detail}</p></div></article>`).join('');

const home = `<section class="hero"><div class="hero-copy"><p class="eyebrow">JOHN SURLES · SOFTWARE & RESEARCH</p><h1>A little structure.<br>A different<br><em>perspective.</em></h1><p class="hero-description">I build web applications, contribute to open source, and explore better ways to connect people with research.</p><div class="hero-actions"><a class="button" href="/work/">Explore my work <span aria-hidden="true">↗</span></a><a class="quiet-link" href="/John-Surles-Resume.pdf">View résumé <span aria-hidden="true">↗</span></a></div></div><div class="sculpture-caption" aria-hidden="true"><span class="caption-rule"></span><span>LIQUID ARCHITECTURE<br>AN EXPLORATION IN FORM</span></div><a class="scroll-cue" href="#selected">A closer look <span aria-hidden="true">↓</span></a></section>
<section class="content-section home-selection" id="selected">${sectionHead('01','Selected work','<span class="meta">Independent projects / 2026</span>')}<div class="project-list">${projectRows}</div></section>
<section class="content-section home-context">${sectionHead('02','In good company')}<div class="context-grid"><a href="/work/#experience" class="context-item"><span class="meta">PREVIOUSLY</span><h3>Procentrix ${arrow}</h3><p>Software engineering internship.<br>Backend APIs, React interfaces, and developer resources.</p></a><a href="/research/" class="context-item"><span class="meta">CURRENTLY</span><h3>Virginia Tech ${arrow}</h3><p>Research, development, and group leadership in VTURCS’s Matching + Semantic Search project.</p></a><a href="/work/#open-source" class="context-item"><span class="meta">IN THE OPEN</span><h3>Contributing back ${arrow}</h3><p>Merged fixes in Microsoft PowerToys, NASA-AMMOS/MMGIS, GitType, and more.</p></a></div></section>`;

const work = `<section class="page-intro"><p class="eyebrow">SELECTED WORK / 2026</p><h1>Ideas, made<br><em>concrete.</em></h1><p>Independent projects, professional experience, and improvements to tools other people use.</p><nav class="section-nav" aria-label="Work sections"><a href="#projects">Projects</a><a href="#experience">Experience</a><a href="#open-source">Open source</a></nav></section>
<section class="content-section" id="projects">${sectionHead('01','Independent projects')}<div class="project-list">${projectRows}</div></section>
<section class="content-section" id="experience">${sectionHead('02','Professional experience')}<article class="experience"><div><span class="meta">JUNE — AUGUST 2026</span><h3>Procentrix</h3><p>Software Engineering Intern</p></div><div class="experience-copy"><h4>Reusable systems.<br>Practical interfaces.</h4><p>Worked across backend architecture, a financial risk assessment interface, and shared engineering resources.</p><ul class="detail-list"><li>Developed a reusable Node.js / TypeScript backend template with SQL Server, separating data-access and service layers.</li><li>Implemented REST APIs with authentication, authorization, input validation, and database-access safeguards.</li><li>Built a React financial risk assessment interface with Microsoft Dataverse and Fluent UI, including reusable master-detail components.</li><li>Published shared engineering resources through a Claude Code plugin marketplace and wrote React / TypeScript scaffolding and Dataverse authentication guidance.</li></ul>${tags(['TypeScript','Node.js','SQL Server','React','Dataverse','Fluent UI'])}</div></article></section>
<section class="content-section" id="open-source">${sectionHead('03','Open-source contributions','<span class="meta">Merged into external projects</span>')}<p class="section-description">Focused fixes, reviewed by maintainers. Each entry links directly to the merged pull request.</p><div class="oss-list">${ossRows}</div></section>`;

const research = `<section class="page-intro"><p class="eyebrow">VIRGINIA TECH / VTURCS</p><h1>Connecting curiosity<br><em>with opportunity.</em></h1><p>Semantic search and intelligent matching to help students discover research opportunities that fit their interests.</p></section>
<section class="content-section research-overview">${sectionHead('01','The project')}<div class="editorial-grid"><div><span class="meta">SEPTEMBER 2026 — PRESENT</span><h3>VTURCS Undergraduate<br>Research Lab</h3><p class="role">Undergraduate Researcher<br>& Group Lead</p></div><div><h4>Matching + Semantic Search</h4><p>I contribute as a researcher and developer, leading one of three student groups under faculty supervision. The project explores how semantic search and intelligent matching can connect students with research opportunities.</p><div class="research-flow" aria-label="Research concept: student interests connect through semantic search and matching to research opportunities"><span>Student<br>interests</span><span aria-hidden="true">→</span><span>Semantic search<br>& matching</span><span aria-hidden="true">→</span><span>Research<br>opportunities</span></div></div></div></section>
<section class="content-section">${sectionHead('02','The work ahead','<span class="status"><span></span> In progress</span>')}<p class="section-description">These are planned responsibilities. Testing results, evaluations, and publications will be added as the work is completed.</p><div class="research-steps"><article><span class="index">01 / TEST</span><h3>Test the system</h3><p>Exercise the search and matching system to understand how it behaves.</p></article><article><span class="index">02 / EVALUATE</span><h3>Evaluate the results</h3><p>Assess the system’s ability to connect student interests with research opportunities.</p></article><article><span class="index">03 / COMMUNICATE</span><h3>Prepare for publication</h3><p>Contribute to documenting the work and preparing it for publication.</p></article></div></section>`;

const about = `<section class="page-intro"><p class="eyebrow">A LITTLE ABOUT ME</p><h1>John Surles.<br><em>Always building.</em></h1><p>I’m a Computer Science student at Virginia Tech. My work spans backend systems, web applications, open-source tools, and undergraduate research.</p></section>
<section class="content-section">${sectionHead('01','Background')}<div class="editorial-grid"><h3>Learning by making.<br>Improving by sharing.</h3><div><p>I build projects for communities I’m part of, from a player-to-player marketplace to OCR automation and Minecraft modding. I also contribute fixes to public projects, working through maintainers’ reviews to improve software beyond my own repositories.</p><p>This summer, I worked as a software engineering intern at Procentrix. I’m now studying at Virginia Tech and contributing to research on semantic search and intelligent matching.</p><div class="inline-links">${ext('GitHub','https://github.com/0utsights')}${ext('LinkedIn','https://www.linkedin.com/in/john-surles-650a16389/')}<a class="text-link" href="/John-Surles-Resume.pdf">Résumé ${arrow}</a></div></div></div></section>
<section class="content-section">${sectionHead('02','Education')}<div class="education-row"><div><h3>Virginia Tech</h3><p>B.S. Computer Science · College of Engineering</p><p class="meta">Current coursework: Intro to Computer Organization II (CS 2506)</p></div><span class="meta">August 2026 — Expected May 2028</span></div><div class="education-row"><div><h3>Northern Virginia Community College</h3><p>Computer Science · GPA 3.55 / 4.0</p></div><span class="meta">September 2024 — May 2026</span></div></section>
<section class="content-section">${sectionHead('03','Tools I work with')}<div class="skill-row"><h3>Languages</h3><p>TypeScript, JavaScript, Python, Java, C#, SQL</p></div><div class="skill-row"><h3>Applications & data</h3><p>React, Next.js, Node.js, FastAPI, PostgreSQL, SQL Server, Prisma, Microsoft Dataverse</p></div><div class="skill-row"><h3>Infrastructure & tools</h3><p>Docker, Terraform, GitHub Actions, Git, Linux, AWS, Oracle Cloud</p></div></section>
<section class="content-section contact-section" id="contact"><p class="eyebrow">GET IN TOUCH</p><h2>Let’s make something<br><em>worth using.</em></h2><a class="contact-email" href="mailto:surlesjohn@outlook.com">surlesjohn@outlook.com ${arrow}</a></section>`;

function projectPage(p) {
 const next=projects[(projects.indexOf(p)+1)%projects.length];
 return `<section class="page-intro project-intro"><a class="back-link" href="/work/">← All work</a><p class="eyebrow">${p.category.toUpperCase()} / ${p.number}</p><h1>${p.title}</h1><p>${p.intro}</p><div class="inline-links">${p.links.map(([label,href])=>ext(label,href)).join('')}</div></section><section class="project-facts"><div><span class="meta">ROLE</span><span>Developer</span></div><div><span class="meta">TIMELINE</span><span>${p.date}</span></div><div><span class="meta">BUILT WITH</span><span>${p.stack.join(' · ')}</span></div></section><section class="content-section">${sectionHead('01','The idea')}<div class="editorial-grid"><h3>${p.summary}</h3><p>${p.problem}</p></div><div class="system-flow" aria-label="${p.flow.join(' to ')}">${p.flow.map((label,i)=>`<div><span class="index">0${i+1}</span><span>${label}</span></div>${i<2?'<span class="flow-arrow" aria-hidden="true">→</span>':''}`).join('')}</div></section><section class="content-section">${sectionHead('02','What I built')}<div class="editorial-grid"><h3>From the core system<br>to the user experience.</h3><ul class="detail-list">${p.contribution.map(item=>`<li>${item}</li>`).join('')}</ul></div></section><section class="content-section">${sectionHead('03','Engineering approach')}<div class="editorial-grid"><h3>How the pieces<br>fit together.</h3><div><p>${p.decision}</p>${tags(p.stack)}<div class="inline-links">${p.links.map(([label,href])=>ext(label,href)).join('')}</div></div></div></section><a class="next-project" href="/work/${next.slug}/"><span class="meta">NEXT PROJECT</span><span>${next.title} ${arrow}</span></a>`;
}

const routes=[
 {path:'/',key:'home',title:'John Surles — Software & Research',description:'Computer Science at Virginia Tech. Software engineering, independent projects, open-source contributions, and undergraduate research.',body:home},
 {path:'/work/',key:'work',title:'Work — John Surles',description:'Independent software projects, a Procentrix internship, and merged contributions to Microsoft PowerToys, NASA-AMMOS/MMGIS, and more.',body:work},
 {path:'/research/',key:'research',title:'Research — John Surles',description:'Undergraduate research and group leadership in VTURCS Matching + Semantic Search at Virginia Tech.',body:research},
 {path:'/about/',key:'about',title:'About — John Surles',description:'Computer Science student at Virginia Tech, former Procentrix software engineering intern, and open-source contributor.',body:about},
 ...projects.map(p=>({path:`/work/${p.slug}/`,key:'project',title:`${p.title} — John Surles`,description:p.summary,body:projectPage(p)})),
];

function page(route) {
 const active=route.key==='project'?'work':route.key;
 const nav=[['Overview','/','home'],['Work','/work/','work'],['Research','/research/','research'],['About','/about/','about']].map(([name,url,key])=>`<a href="${url}"${key===active?' aria-current="page"':''}>${name}</a>`).join('');
 return `<!doctype html>
<html lang="en" data-page="${route.key}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#e9e7e0"><title>${route.title}</title><meta name="description" content="${route.description}"><link rel="canonical" href="https://johnsurles.com${route.path}"><meta property="og:type" content="website"><meta property="og:title" content="${route.title}"><meta property="og:description" content="${route.description}"><meta property="og:url" content="https://johnsurles.com${route.path}"><meta name="twitter:card" content="summary"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><link rel="preload" href="/fonts/editorial.woff2" as="font" type="font/woff2" crossorigin><link rel="stylesheet" href="/styles.css"><script type="module" src="/app.js"></script></head>
<body><a class="skip-link" href="#main">Skip to content</a><div class="ambient" aria-hidden="true"><canvas id="sculpture"></canvas><div class="ambient-shade"></div></div><header class="site-header"><a class="wordmark" href="/" aria-label="John Surles, home">john surles<span>/</span></a><nav class="main-nav" aria-label="Main navigation">${nav}</nav><a class="header-contact" href="mailto:surlesjohn@outlook.com">Let’s talk ${arrow}</a></header><main id="main" tabindex="-1">${route.body}</main><footer class="site-footer"><div class="footer-top"><a class="wordmark" href="/">john surles<span>/</span></a><div class="footer-links">${ext('GitHub','https://github.com/0utsights')}${ext('LinkedIn','https://www.linkedin.com/in/john-surles-650a16389/')}<a class="text-link" href="mailto:surlesjohn@outlook.com">Email ${arrow}</a><a class="text-link" href="/John-Surles-Resume.pdf">Résumé ${arrow}</a></div></div><div class="footer-bottom"><span>© 2026 John Surles · Blacksburg, Virginia</span><div class="preferences" hidden><button id="motion-toggle" type="button" aria-pressed="false">Pause motion</button><span aria-hidden="true">/</span><button id="sound-toggle" type="button" aria-pressed="false">Sound off</button></div><span>Made with intention.</span></div></footer><noscript><style>.ambient{background:radial-gradient(ellipse at 85% 25%,#b1b4ac55,transparent 60%)}.sculpture-caption{display:none}</style></noscript></body></html>`;
}
for (const route of routes) {
 const dir=join(output,route.path);await mkdir(dir,{recursive:true});await writeFile(join(dir,'index.html'),page(route));
}
// Preserve the old personal route without perpetuating outdated personal copy.
await mkdir(join(output,'personal'),{recursive:true});
await writeFile(join(output,'personal/index.html'),`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta http-equiv="refresh" content="0;url=/about/"><link rel="canonical" href="https://johnsurles.com/about/"><title>About — John Surles</title></head><body><a href="/about/">Continue to About John Surles</a></body></html>`);
await writeFile(join(output,'404.html'),page({path:'/404.html',key:'about',title:'Page not found — John Surles',description:'This page could not be found.',body:'<section class="page-intro"><p class="eyebrow">404 / A SMALL DETOUR</p><h1>Back to<br><em>familiar ground.</em></h1><p>That page isn’t here. You can return to the overview or explore my selected work.</p><div class="inline-links"><a class="button" href="/">Return home ↗</a><a class="text-link" href="/work/">Explore work ↗</a></div></section>'}));
await writeFile(join(output,'robots.txt'),'User-agent: *\nAllow: /\nSitemap: https://johnsurles.com/sitemap.xml\n');
await writeFile(join(output,'sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${routes.map(r=>`<url><loc>https://johnsurles.com${r.path}</loc></url>`).join('')}</urlset>`);
console.log(`Built ${routes.length} static pages, legacy redirect, 404, and public assets.`);
